users/main.py
# -*- encoding: utf-8 -*-
# this holds all the flask-login specific logic (+ url mapping an rendering templates)
# for the user management
# author: harald schilly <harald.schilly@univie.ac.at>

import pymongo
ASC = pymongo.ASCENDING
import flask
from functools import wraps
from base import app, getDBConnection
from flask import render_template, request, abort, Blueprint, url_for, make_response
from flaskext.login import login_required, login_user, current_user, logout_user

login_page = Blueprint("users", __name__, template_folder='templates')
import utils
logger = utils.make_logger(login_page)

import re
allowed_usernames = re.compile("^[a-zA-Z0-9._-]+$")

from flaskext.login import LoginManager
login_manager = LoginManager()

import pwdmanager
from pwdmanager import LmfdbUser, LmfdbAnonymousUser

# TODO update this url, needed for the user login token
base_url = "http://www.l-functions.org"

@login_manager.user_loader
def load_user(userid):
  from pwdmanager import LmfdbUser
  return LmfdbUser(userid) 

login_manager.login_view = "users.info"

# this anonymous user has the is_admin() method
login_manager.anonymous_user = LmfdbAnonymousUser

# globally define the user and username
@app.context_processor
def ctx_proc_userdata():
  userdata = {}
  userdata['username'] = 'Anonymous' if current_user.is_anonymous() else current_user.name
  userdata['user_is_authenticated'] =  current_user.is_authenticated()
  userdata['user_is_admin'] = current_user.is_admin()
  return userdata

# blueprint specific definition of the body_class variable
@login_page.context_processor
def body_class():
  return { 'body_class' : 'login' }

# the following doesn't work as it should, also depends on blinker python lib
# flask signal when a user logs in. we record the last logins in the user's data
# http://flask.pocoo.org/docs/signals/
#def log_login_callback(cur_app, user = None):
#  cur_user = user or current_user 
#  logger.info(">> curr_app: %s   user: %s" % (cur_app, cur_user))
#
#from flaskext.login import user_logged_in, user_login_confirmed
#user_logged_in.connect(log_login_callback)
#user_login_confirmed.connect(log_login_callback)


def base_bread():
  return [('Users', url_for(".list"))]

@login_page.route("/")
@login_required
def list():
  import pwdmanager
  users = pwdmanager.get_user_list()
  # trying to be smart and sorting by last name
  users = sorted(users, key=lambda x : x[1].split(" ")[-1].lower())
  bread = base_bread()
  return render_template("user-list.html", title="All Users", 
      users = users, bread = bread)

@login_page.route("/myself")
def info():
  info = {}
  info['login'] = url_for(".login")
  info['logout'] = url_for(".logout")
  info['user'] = current_user
  info['next'] = request.referrer
  return render_template("user-info.html", 
      info = info, title="Userinfo", 
      bread = base_bread() + [("Myself", url_for(".info"))])

# ./info again, but for POST!
@login_page.route("/info", methods = ['POST'])
@login_required
def set_info():
  for k,v in request.form.iteritems():
    setattr(current_user, k, v)
  current_user.save()
  flask.flash("Thank you for updating your details!")
  return flask.redirect(url_for(".info"))

@login_page.route("/profile/<userid>")
@login_required
def profile(userid):
  getDBConnection().knowledge.knowls.ensure_index('title')
  user = LmfdbUser(userid)
  bread = base_bread() + [(user.name, url_for('.profile', userid=user.get_id()))]
  userknowls = getDBConnection().knowledge.knowls.find({'authors' : userid}, fields=['title']).sort([('title', ASC)])
  userfiles = getDBConnection().upload.fs.files.find({'metadata.uploader_id' : userid, 'metadata.status': 'approved'})
  userfilesmod = getDBConnection().upload.fs.files.find({'metadata.uploader_id' : userid, 'metadata.status': 'unmoderated'})
  return render_template("user-detail.html", user=user, 
      title="%s" % user.name, bread= bread, userknowls = userknowls, userfiles = userfiles, userfilesmod = userfilesmod)

@login_page.route("/login", methods = ["POST"])
def login(**kwargs):
  bread = base_bread() + [ ('Login', url_for('.login')) ]
  # login and validate the user …
  # remember = True sets a cookie to remmeber the user
  name      = request.form["name"]
  password  = request.form["password"]
  next      = request.form["next"]
  remember  = True if request.form["remember"] == "on" else False
  user      = LmfdbUser(name)
  if user and user.authenticate(password):
    login_user(user, remember=remember) 
    flask.flash("Hello %s, your login was successful!" % user.name)
    logger.info("login: '%s' - '%s'" % (user.get_id(), user.name))
    return flask.redirect(next or url_for(".info"))
  flask.flash("Oops! Wrong username or password.", "error")
  return flask.redirect(url_for(".info"))

def admin_required(fn):
  """
  wrap this around those entry points where you need to be an admin.
  """
  @wraps(fn)
  @login_required
  def decorated_view(*args, **kwargs):
    logger.info("admin access attempt by %s" % current_user.get_id())
    if not current_user.is_admin():
      return flask.abort(403) # 401 = access denied
    return fn(*args, **kwargs)
  return decorated_view

def get_user_token_coll():
  return getDBConnection().userdb.tokens

@login_page.route("/register")
def register_new():
  q_admins = getDBConnection().userdb.users.find({'admin' : True})
  admins =', '.join((_['full_name'] or _['_id'] for _ in q_admins))
  return "You have to contact one of the Admins: %s" % admins

@login_page.route("/register/new")
@login_page.route("/register/new/<int:N>")
@admin_required
def register(N = 10):
  N = 100 if N > 100 else N
  from datetime import datetime, timedelta
  now    = datetime.utcnow()
  tdelta = timedelta(days=1)
  exp    = now + tdelta
  import random
  tokens = [ str(random.randrange(1e20,1e21)) for _ in range(N) ]
  for t in tokens:
    get_user_token_coll().save({'_id' : t, 'expire':exp})
  urls   = [ "%s%s" % (base_url, url_for(".register_token", token = _)) for _ in tokens ]
  resp = make_response('\n'.join(urls))
  resp.headers['Content-type'] = 'text/plain'
  return resp

def delete_old_tokens():
  from datetime import datetime, timedelta
  now    = datetime.utcnow()
  tdelta = timedelta(days=8)
  exp    = now + tdelta
  get_user_token_coll().remove({'expire': { '$gt' : exp}})

@login_page.route("/register/<token>", methods = ['GET', 'POST'])
def register_token(token):
  delete_old_tokens()
  token_exists = get_user_token_coll().find({'_id' : token}).count() == 1
  if not token_exists:
    flask.abort(401)
  bread = base_bread() + [('Register', url_for(".register_new"))]
  if request.method == "GET":
    return render_template("register.html", title="Register", bread=bread, next=request.referrer or "/", token=token)
  elif request.method == 'POST':
    name   = request.form['name']
    if not allowed_usernames.match(name):
      flask.flash("""Oops, usename '%s' is not allowed.
                  It must consist of lower/uppercase characters, 
                  no spaces, numbers or '.', '_' and '-'.""" % name, "error")
      return flask.redirect(url_for(".register_new"))
    
    pw1    = request.form['password1']
    pw2    = request.form['password2']
    if pw1 != pw2:
      flask.flash("Oops, passwords do not match!", "error")
      return flask.redirect(url_for(".register_new"))

    if len(pw1) <= 3:
      flask.flash("Oops, password too short. Minimum 4 characters please!", "error")
      return flask.redirect(url_for(".register_new"))

    full_name  = request.form['full_name']
    email      = request.form['email']
    next       = request.form["next"]

    if pwdmanager.user_exists(name):
      flask.flash("Sorry, user ID '%s' already exists!" % name, "error")
      return flask.redirect(url_for(".register_new"))

    newuser             = pwdmanager.new_user(name, pw1)
    newuser.full_name   = full_name
    newuser.email       = email
    newuser.save()
    login_user(newuser, remember=True) 
    flask.flash("Hello %s! Congratulations, you are a new user!" % newuser.name)
    get_user_token_coll().remove({'_id' : token})
    logger.debug("removed login token '%s'" % token)
    logger.info("new user: '%s' - '%s'" % (newuser.get_id(), newuser.name))
    return flask.redirect(next or url_for(".info"))


@login_page.route("/logout")
@login_required
def logout():
  bread = base_bread() + [ ('Login', url_for('.logout')) ]
  logout_user()
  flask.flash("You are logged out now. Have a nice day!")
  return flask.redirect(request.args.get("next") or request.referrer or url_for('.info'))

@login_page.route("/admin")
@login_required
@admin_required
def admin():
  return "success: only admins can read this!"

templates/DegreeNavigateL.html
{% extends 'homepage.html' %}

{% block content %}


{% if info.degree==1 %}
<div>There are only {{ KNOWL('lfunction.alldegree1.proof', title='two types') }} of degree 1 L-functions:</div>
<h3>1. The <a href="/L/Riemann">Riemann zeta function</a></h3>
<div>
The {{ KNOWL('lfunction.riemann', title='Riemann zeta function,') }}
<a href="/L/Riemann">$\zeta(s)$</a>, was introduced by {{ KNOWL('bio.riemann', title='Riemann') }} in the mid-1800s as a tool to study
the distribution of prime numbers.
</div>

<h3>2. Dirichlet L-functions associated to a primitive {{ KNOWL('character.dirichlet', title='Dirichlet character') }}</h3>
{{ KNOWL('lfunction.dirichlet', title='Dirichlet L-functions') }} were introduced by {{ KNOWL('bio.dirichlet', title='Dirichlet') }} in the mid-1800s as a tool to study
prime numbers in arithmetic progressions.
{{info.contents[0]|safe}}

{% endif %}

{% if info.degree==2 %}

<h2>Automorphic Objects</h2>

<div>There are two known types of primitive degree 2 L-functions that arise from automorphic objects:</div>
<ul>
<li><a href="degree2#GL2_Q_Holomorphic">$L(s, f)$: the L-function of a holomorphic newform in $S_k(\Gamma_0(N))$</a>
</li>
<li><a href="degree2#GL2_Q_Maass">$L(s, f)$: the L-function of a Maass cusp form on  $\Gamma_0(N)$</a></li>
</ul>

<h2>Geometric Objects</h2>

<div>There is one known type of primitive degree 2 L-function that arises from a geometric object:</div>
<ul>
<li>
<a href="degree2#EllipticCurve_Q">$L(s, E)$: the L-function of an elliptic curve $E$ over $\mathbb{Q}$.</a></li>
</ul>
<h2>Available Examples</h2>

<h3 id="GL2_Q_Holomorphic">L-functions of holomorphic cusp forms with trivial character</h3>

{{info.contents[1]|safe}}

<h3 id="GL2_Q_Maass">Maass cusp forms on GL(2,$\mathbb{Z}$)</h3>

{{info.contents[2]|safe}}

<h3 id="EllipticCurve_Q">Elliptic Curves over $\mathbb{Q}$</h3>

{{info.contents[0]|safe}}



{% endif %}

{% if info.degree==3 %}
<div>The known types of primitive degree 3 L-functions are:</div>
<p>
<div>$L(s, f, \mathrm{sym}^2)$: the symmetric square of a degree 2 L-function</div>
 <p>
<div>$L(s,f)$: standard L-function of a cusp form on GL(3)</div>


<h2>Available Examples:</h2>

{{info.contents|safe}}

{% endif %}
 
{% if info.degree==4 %}
<div>The known types of primitive degree 4 L-functions are:</div>
<p>
<div>$L(s, f, \mathrm{sym}^3)$: the symmetric cube L-function of a cusp form on GL(2)</div>
        <p>

        <div>$L(s, f, \mathrm{sym}^3)$: the symmetric cube L-function of a cusp form on GL(2)</div>
        <p>
	<div>$L(s, F, \mathrm{spin})$: spin L-function of a Siegel modular form on GSp(4) (genus 2)</div>
	<p>
	<div>$L(s,f)$: standard L-function of a cusp form on the Picard group SL(2,Z[i])</div>
	<p>
	<div>$L(s,f)$: standard L-function of a cusp form on Sp(4)</div>

	<p>
	<div>$L(s,f)$: standard L-function of a cusp form on GL(4)</div>
	<p>
	<div>$L(s,E)$: L-function of an elliptic curve over a quadratic field</div>
	<p>
	<div>$L(s,f)$: standard L-function of a Hilbert modular form on GL(2) over a real quadratic field</div>
        <p>

<h2>Available Examples:</h2>

<!-- <h3>Maass cusp forms on Sp(4,Z)</h3>
<div>These satisfy a functional equation with $\Gamma$-factors
\begin{equation}
\Gamma_R(s + i \mu_1) 
\Gamma_R(s + i \mu_2) 
\Gamma_R(s - i \mu_1) 
\Gamma_R(s - i \mu_2) 
\end{equation}
with $0 \le \mu_2 \le \mu_1$.
</div>
<div>The dots in the plot correspond to $(\mu_1,\mu_2)$ for Sp(4,Z) L-functions
which have been found by a computer search.</div>
<embed src="/static/images/Sp4.svg" width="470" height="330">
<br>
<h3>Maass cusp forms on SL(4,Z)</h3>
<div>These satisfy a functional equation with $\Gamma$-factors
\begin{equation}
\Gamma_R(s + i \mu_1) 
\Gamma_R(s + i \mu_2) 
\Gamma_R(s - i \mu_3) 
\Gamma_R(s - i \mu_4) 
\end{equation}
where $\mu_1 + \mu_2 = \mu_3 + \mu_4$.
</div>
<div>The dots in the plot correspond to $(\mu_1,\mu_2)$ for SL(4,Z) L-functions
which have been found by a computer search.</div>
<embed src="/static/images/SL4.svg" width="520" height="360"> -->

{{info.contents|safe}}

{% endif %}
 
{% endblock %}

templates/Lfunction.html
{% extends 'homepage.html' %}

{% block content %}
 <h2> {{ KNOWL('alg.dirichlet_series', title='Dirichlet series') }}</h2>
 <div>\[{{ dirichlet }}\]</div>

 <h2>{{ KNOWL('lfunction.functional_equation',title='Functional equation') }}</h2>
 
 <div id="functionalEqText">\[{{ functionalequation }}\]</div>
 <div>
   {{ KNOWL('lfunction.selbergdata', title="Selberg data") }}: ${{ functionalequationSelberg }}$</div>
 
 
 <h2>{{ KNOWL('lfunction.euler_product', title='Euler product') }}</h2>
 <div>\[{{ eulerproduct }}\]</div>

 <h2> Imaginary part of the first few zeroes on the {{ KNOWL('lfunction.critical_line', title='critical line') }}</h2>

 {% if zeroeslink %}
     <div><span id="zeroes"></span></div>
 {% else %}
     <div>Not enough Dirichlet series coefficients to compute zeros.</div>
 {% endif %}

 {% if sv1 and sv12 %}
     <h2>Special Values</h2>
     <div>
      {{ sv12 }}<br>
      {{ sv1 }}<br>
     </div>
 {% else %}
      <div>Not enough Dirichlet series coefficients to compute special values.</div>
 {% endif %}

 {% if plotlink %}
    <h2> Graph of the {{ KNOWL('lfunction.zfunction', title='$Z$-function') }} along the {{ KNOWL('lfunction.critical_line', title='critical line') }} </h2>
    <img src="{{ plotlink|safe }}" >
 {% else %}
    <div>Not enough Dirichlet series coefficients to make a graph.</div>
 {% endif %}

<script type="text/javascript">
  $(function() {
      $("#zeroes").load("{{ zeroeslink|safe }}");
  });
</script>

{% endblock %}

templates/LfunctionNavigate.html
{% extends 'homepage.html' %}

{% block content %}
<h2> Browse {{KNOWL('lfunction', title='L-functions')}} by {{KNOWL("lfunction.underlying_object",title="underlying object")}}</h2>
<table>
{% for i in info.l: %}
<tr>
  {% for t in info.type_table[i]: %}
  <td><a  style="padding: 5px;" href="{{t.link}}">{{t.title|safe}}</a></td>
  {% endfor %}
<tr>
{% endfor %}
</table>

<h2> Browse {{KNOWL('lfunction', title='L-functions')}} by {{KNOWL('lfunction.degree', title='degree') }}</h2>
<table>
 <tr>
    <td style="text-align: center;">
       <a style="width: 2em;" {{url_for('render_Lfunction', arg1 = 'degree1')}}>1</a>
       <a style="width: 2em;" {{url_for('render_Lfunction', arg1 = 'degree2')}}>2</a>
       <a style="width: 2em;" {{url_for('render_Lfunction', arg1 = 'degree3')}}>3</a>
       <a style="width: 2em;" {{url_for('render_Lfunction', arg1 = 'degree4')}}>4</a>
    </td>
 </tr>

</table>
<br />

<h2> Search </h2>


<form action="{{url_for(".LfunctionDB.query")}}" method=get>
<div>
Enter values into one or more boxes to restrict the search.
</div>
<table>
<tr>
<td>{{ KNOWL('lfunction.degree', title='Degree') }}</td><td> <input type='text' name='degree' size = "4" placeHolder='2'></td><td><span class="formexample"> e.g. 2 </span></td>

</tr>

<tr>
<td>{{ KNOWL('lfunction.signature', title='Signature') }}</td><td> <input type='text' name='signature' size = '4' placeHolder='[0,1]'></td><td><span class="formexample"> e.g. [0,1] </span></td>
</tr>

<tr>
<td>{{ KNOWL('lfunction.level', title='Level') }} </td><td><input type='text' name='level' size='4' placeHolder='656'></td><td><span class="formexample"> e.g. 656 </span></td>
</tr>
<tr>

<tr>
<td>{{ KNOWL('lfunction.zeros', title='Lowest zero') }} is greater than</td><td> <input type='text' size='4' name='zerolowerbound' placeHolder='1.1'></td><td> and less than </td><td><input type='text' size='4' name='zeroupperbound' placeHolder='2.1'></td><td><span class="formexample"> e.g. 1.1 and 2.1 </span></td>
</tr>
<tr>
<td>{{ KNOWL('lfunction.central_value', title='Central value') }} is around</td><td> <input type='text' name='critical_value' size='4' placeHolder='0.5'></td><td><span class="formexample"> e.g. 0.5 </span></td>
</tr>

<tr>
<td>{{ KNOWL('lfunction.special_values', title='Value') }} at 1 is around</td><td> <input type='text' name='special_value' size='4' placeHolder='3.1'></td><td><span class="formexample"> e.g. 3.1 </span></td>
</tr>
</table>
<p>
<button type='submit' value='Search' >Search
</p>
</form>

{% endblock %}

templates/LfunctionSimple.html
{% extends 'homepage.html' %}

<!-- No idea what this does. Should be documented. Paul -->

{% block content %}
<div class="announce">
 {{ content }}
</div>
<div align="center">
<input type=button value="Back" onClick="history.go(-1)">
</div>
{% endblock %}

templates/acknowledgment.html
{% extends 'homepage.html' %}

{% block content %}

<h1>Programmers</h1>
<div>
<ul>
  <li>Matt Alderson</li>
  <li>Salman Baig</li>
  <li>Jennifer Balakrishnan</li>
  <li>Jennifer Beineke</li>
  <li>Jonathan Bober</li>
  <li>Andrew Booker</li>
  <li>Robert Bradshaw</li>
  <li>Alina Bucur</li>
  <li>Henri Cohen</li>
  <li>Brian Conrey</li>
  <li>John Cremona</li>
  <li>Paul-Olivier Dehaye</li>
  <li>Tim Dokchitser</li>
  <li>David Farmer</li>
  <li>Marcus Fraczek</li>
  <li>Ralph Furmaniak</li>
  <li>Jonthan Hanke</li>
  <li>Bill Hart</li>
  <li>Duc Khiem Huynh</li>
  <li>John Jones</li>
  <li>Kiran Kedlaya</li>
  <li>Sally Koutsoliotas</li>
  <li>Stefan Lemurell</li>
  <li>Robert Miller</li>
  <li>Andrew Pollington</li>
  <li>Rishikesh</li>
  <li>Michael Rubinstein</li>
  <li>Nathan Ryan</li>
  <li>Ralf Schmidt</li>
  <li>Harald Schilly</li>
  <li>Nils-Peter Skoruppa</li>
  <li>William Stein</li>
  <li>Fredrik Stromberg</li>
  <li>Holly Swisher</li>
  <li>Gonzalo Tornaria</li>
  <li>Holger Then</li>
  <li>John Voight</li>
  <li>Lynne Walling</li>
  <li>Trevor Wooley</li>
  <li>David Yuen</li>
</ul>
</div>

<h1>Sponsors</h1>

<div>{{ lipsum(1) }}</div>

<h1>Software</h1>

<div>{{ lipsum(1) }}</div>

{% endblock %}

templates/base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Content-Language" Content="en">

<title>{% if title %}{{ title|striptags }} - {% endif %}LMFDB</title>
<link href="{{ url_for('css') }}" rel="stylesheet" type="text/css" /> 

<script type="text/javascript" src="{{ url_for('static', filename='jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='jquery.watermark.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='lmfdb.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='showdown.min.js') }}"></script>

<script type="text/javascript" src="{{ url_for('static', filename='jquery.dataTables.js') }}"></script> 
<script type="text/javascript" src="{{ url_for('static', filename='jquery-ui-1.8.14.custom.min.js') }}"></script> 
<script type="text/javascript" src="https://www.google.com/jsapi"></script> 
 
<link rel="stylesheet" href="{{ url_for('static', filename='jquery-ui-1.8.14.custom.css') }}" type="text/css"/> 



<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  extensions: ["tex2jax.js","TeX/AMSmath.js","TeX/AMSsymbols.js"],
  jax: ["input/TeX","output/HTML-CSS"],
  tex2jax: {
    inlineMath: [['$','$'],["\\(","\\)"]],
    processEscapes: true,
  },
  "HTML-CSS": { scale: 85 },
  menuSettings: { zscale: "150%", zoom: "Double-Click" }
});
</script>
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js"></script>
{# append this: ?config=default if the script complains about a missing config #}

{# the defs for the knowls, need to be after mathjax, before analytics #}
{% include "knowl-defs.html" %}
{% from "knowl-defs.html" import KNOWL with context %}
{% from "knowl-defs.html" import KNOWL_LINK with context %}
{% from "knowl-defs.html" import KNOWL_INC with context %}
{% from "knowl-defs.html" import TEXT_DATA with context %}

<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-19138192-1']);
_gaq.push(['_setDomainName', 'none']);
_gaq.push(['_setAllowLinker', true]);
_gaq.push(['_trackPageview']);
_gaq.push(['_trackPageLoadTime']);

(function() {
 var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
 ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
 var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
</head>

<body class="{{ body_class }}">

{# 
<div style="width: 100%; background-color: #f88; text-align: center; padding: 3px;margin-bottom:0px; border-bottom: 2px solid red;">
Pre-Release Version. Feedback via 
<a href="mailto:farmer@aimath.org" subject="[LMFDB] ">direct e-mail</a> or 
<a href="http://groups.google.com/group/lmdb" target="_blank">discuss online</a>.</div>
#}

{% block body -%}{%- endblock body %}
</body>
</html>

templates/form.html
{% extends 'homepage.html' %}

{% block title %}Get EC{% endblock %}

{% block body %}

<div id = "header">
Form to get an EC
</div>

<div id = "content">
<h2>Form to get an EC</h2>

<form name="input" action="{{ url_for('EC_toplevel') }}" method="get">
Conductor: <input type="text" name="conductor" value="10" />
<button type="submit" value="Submit" />
</form>

</div>

{% endblock %}

templates/index.html
{% extends "homepage.html" %}
{% block content %}

<div class="announce">
Welcome! The <b>L</b>-function and <b>M</b>odular 
<b>F</b>orms <b>D</b>ata<b>B</b>ase 
project is a collaborative
effort by Number Theorists to share, contextualize and improve data
and theorems.
</div>

<h1>Sections</h1>

 <ul>
  <li><a href="{{ url_for('render_Lfunction') }}">$L$-functions and Zeta-functions</a></li>
  <li>Elliptic Curves</li>
  <ul>
   <li><a href="{{ url_for('EC_toplevel') }}  ">Elliptic Curves/\(\mathbb Q\)</a></li>
  </ul>

  <li><a href="{{ url_for('number_field_render_webpage') }}">Number Fields</a></li>

  <li>Characters</li>
  <ul>
   <li><a href="{{ url_for('render_Character') }} ">Dirichlet Characters</a></li>
  </ul>

  <li><a class="mf"    href="{{ url_for('mf.modular_form_main_page') }}">Modular Forms</a></li>
  <ul>
   <li><a class="emf"  href="{{ url_for('emf.render_elliptic_modular_forms') }}">Holomorphic Cusp Forms  on \(GL(2)\)</a></li>
   <li><a class="mwf"  href="{{ url_for('mwf.render_maass_waveforms') }}">Maass Forms on \(GL(2)\)</a></li>
   <li><a              href="{{ url_for('ModularForm_GSp4_Q_top_level') }}">Siegel Modular forms</a> </li>
   <li><a class="mwfp" href="{{ url_for('mwfp.render_picard_maass_forms') }}">Maass Forms on the Picard Group \(SL_2(Z[i])\)</a></li>
   <li><a              href="{{ url_for('hilbert_modular_form_render_webpage') }}">Hilbert Modular Forms</a></li>
  </ul>
 </ul>

<h1>Search</h1>
 <ul>
  <li><a href="{{ url_for('LfunctionDB.query', zerolowerbound=1.1, zeroupperbound=2.1) }}">Search $L$-functions</a></li>
 </ul>

<h1>Misc Pages</h1>
<ul>
 <li><a href="{{ url_for("knowledge.index") }}">Knowledge</a></li>
 <li>What is a {{ KNOWL("doc.knowl") }}? Click on it!</li>
 <li><a href="{{ url_for("users.list") }}">User Management</a>:
 {% if user_is_authenticated -%}
   you are "<a href="{{ url_for('users.info') }}">{{username}}</a>"
 {%- endif %}
 </li>
 <li><a href="{{ url_for("about") }}">About</a></li>
 <li><a href="{{ url_for("acknowledgment") }}">Acknowledgment</a></li>
</ul>

<h1>Data Uploading</h1>
<ul>
<li><a href="{{ url_for("upload.viewAll")}}">View uploaded data</a></li>
{% if user_is_authenticated %}
 <li><a href="{{ url_for("upload.index") }}">Upload data</a></li>
 {% if user_is_admin %}
  <li><a href="{{ url_for("upload.admin") }}">Moderate uploaded files</a></li>
 {% endif %}
{% endif %}
</ul>

{% if user_is_authenticated %}
<h1>Raw</h1>
<ul>
<li><a href="/raw">raw</a>
</ul>
{% endif %}

{% endblock %}

templates/not_yet_implemented.html
{% extends "homepage.html" %}

{% block content %}

Sorry. This feature is not yet implemented.  <a href="{{ request.referrer }}">jump back</a>.

{% endblock %}